"""Append Spanish translations for remaining articles 6-7 to es_blog_bodies.json"""
import json

with open('scripts/es_blog_bodies.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Article 6: LFP vs NMC Battery
data["f9c13832-8b11-4db4-9eb1-049c6fb91e98"] = (
    "Al disenar un sistema de almacenamiento de energia en baterias (BESS), una de las decisiones mas "
    "fundamentales es la eleccion de la quimica de la bateria. Las dos quimicas dominantes en el mercado "
    "actual son **LFP (fosfato de hierro y litio)** y **NMC (niquel manganeso cobalto)**. Aunque ambas "
    "son de iones de litio, sus diferencias en seguridad, costo, vida util y rendimiento las hacen "
    "adecuadas para aplicaciones muy diferentes.\n\n"
    "Este articulo proporciona una comparacion basada en datos para ayudar a desarrolladores de proyectos, "
    "contratistas EPC e integradores de sistemas a tomar la decision correcta.\n\n"
    "## Comprendiendo las Quimicas\n\n"
    "### Que es LFP?\n\n"
    "**LFP (LiFePO4)** utiliza fosfato de hierro y litio como material del catodo. Los fuertes enlaces "
    "covalentes entre hierro, fosforo y oxigeno hacen que la estructura cristalina sea excepcionalmente "
    "estable, incluso a altas temperaturas o bajo dano fisico.\n\n"
    "### Que es NMC?\n\n"
    "**NMC (LiNixMnyCo1-x-yO2)** combina niquel (para densidad energetica), manganeso (para estabilidad) "
    "y cobalto (para rendimiento de potencia) en el catodo. Las proporciones comunes incluyen NMC 811, "
    "NMC 622 y NMC 532. El alto contenido de niquel permite una mayor densidad energetica pero reduce "
    "la estabilidad termica.\n\n"
    "## Seguridad: El Factor Decisivo para Almacenamiento Estacionario\n\n"
    "La seguridad es donde LFP y NMC divergen mas dramaticamente, y es la razon principal por la que "
    "LFP se ha convertido en el estandar de la industria para almacenamiento estacionario de energia.\n\n"
    "| Parametro de Seguridad | LFP | NMC |\n"
    "|------------------------|-----|-----|\n"
    "| Temperatura de inicio de fuga termica | 270-300 C | 150-200 C |\n"
    "| Temperatura maxima durante fuga | ~400 C | ~700-900 C |\n"
    "| Liberacion de oxigeno durante descomposicion | Despreciable | Significativa (alimenta el fuego) |\n"
    "| Dificultad de supresion de incendios | Moderada (tendencia autoextinguible) | Alta (crea su propio oxigeno) |\n"
    "| Clasificacion de seguridad | Clase 9 mercancias peligrosas | Clase 9, perfil de riesgo mas alto |\n\n"
    "**Perspectiva critica:** Cuando las celdas NMC entran en fuga termica, el catodo se descompone "
    "y libera oxigeno, esencialmente alimentando su propio fuego. La estructura cristalina de olivino "
    "de LFP no libera oxigeno, haciendo que los incendios sean mucho mas faciles de contener.\n\n"
    "## Vida Util de Ciclos: La Ventaja Economica de LFP\n\n"
    "| Parametro de Vida Util | LFP | NMC |\n"
    "|------------------------|-----|-----|\n"
    "| Vida util de ciclos (100% DoD, 25 C) | 6,000-8,000+ | 2,000-4,000 |\n"
    "| Vida calendario | 15-20 anos | 8-12 anos |\n"
    "| Degradacion anual | 1.5-2.5% | 3-5% |\n"
    "| Retencion de capacidad al final de vida | >=70% (garantia tipica) | >=60% (garantia tipica) |\n\n"
    "Para una aplicacion de almacenamiento de energia tipica con un ciclo por dia, LFP ofrece "
    "efectivamente entre 2 y 3 veces mas anos de servicio util en comparacion con NMC. Esto se traduce "
    "directamente en un costo nivelado de almacenamiento (LCOS) mas bajo, incluso si el costo inicial "
    "de LFP es similar o ligeramente superior.\n\n"
    "## Costo: Panorama Actual del Mercado (2026)\n\n"
    "| Componente de Costo | LFP | NMC |\n"
    "|---------------------|-----|-----|\n"
    "| Costo de celda ($/kWh) | $40-55 | $55-75 |\n"
    "| Costo de paquete ($/kWh) | $75-95 | $90-120 |\n"
    "| Costo del sistema BESS ($/kWh) | $250-350 | $300-450 |\n"
    "| Costo del sistema de refrigeracion | Menor (menos gestion termica) | Mayor (refrigeracion activa) |\n\n"
    "LFP disfruta actualmente de una ventaja de costo del 15-25% sobre NMC a nivel de sistema, "
    "impulsada por menores costos de materia prima (sin cobalto ni niquel), procesos de fabricacion "
    "mas simples y menores requisitos de gestion termica.\n\n"
    "## Densidad Energetica: Donde NMC Aun Domina\n\n"
    "| Metrica de Densidad | LFP | NMC |\n"
    "|---------------------|-----|-----|\n"
    "| Densidad energetica de celda (Wh/kg) | 140-180 | 200-260 |\n"
    "| Densidad energetica de paquete (Wh/kg) | 100-140 | 150-200 |\n"
    "| Densidad volumetrica (Wh/L) | 300-400 | 500-700 |\n\n"
    "Para vehiculos electricos donde cada kilogramo y litro importa, NMC sigue siendo la opcion "
    "dominante. Pero para almacenamiento estacionario - donde el espacio y el peso rara vez son "
    "factores limitantes - la menor densidad energetica de LFP no es una desventaja practica.\n\n"
    "## Impacto Ambiental y Cadena de Suministro\n\n"
    "| Factor | LFP | NMC |\n"
    "|--------|-----|-----|\n"
    "| Contenido de cobalto | 0% | 10-20% |\n"
    "| Riesgo etico en cadena de suministro | Bajo | Alto (mineria de cobalto) |\n"
    "| Reciclabilidad | Alta (proceso mas simple) | Moderada (recuperacion compleja) |\n"
    "| Abundancia de materia prima | Alta (hierro, fosforo) | Moderada (niquel, cobalto) |\n\n"
    "El contenido cero de cobalto de LFP elimina los riesgos reputacionales y de cadena de suministro "
    "asociados con la mineria de cobalto, un factor cada vez mas importante para inversores "
    "institucionales y proyectos financiados con criterios ESG.\n\n"
    "## Cuando Elegir Cada Quimica\n\n"
    "### Elija LFP Cuando:\n"
    "- Almacenamiento estacionario de energia (C&I, utility, residencial)\n"
    "- La seguridad es primordial (entornos urbanos, instalaciones interiores)\n"
    "- Se requiere larga vida util de ciclos (>6,000 ciclos)\n"
    "- El presupuesto y el costo total de propiedad son prioridades\n"
    "- Se requiere cumplimiento ESG y cadena de suministro libre de cobalto\n\n"
    "### Elija NMC Cuando:\n"
    "- Las limitaciones de espacio/peso son extremas (dispositivos portatiles)\n"
    "- Se requiere alta densidad de potencia (algunas aplicaciones de regulacion de frecuencia)\n"
    "- EV y aplicaciones moviles donde el peso impacta la autonomia\n"
    "- Aplicaciones especializadas donde se justifica un costo premium\n\n"
    "## El Veredicto\n\n"
    "Para almacenamiento estacionario de energia, **LFP es el claro ganador** en todas las metricas "
    "que importan: seguridad, vida util, costo total de propiedad y huella ambiental. La transicion "
    "de la industria de NMC a LFP para BESS estacionario es una de las tendencias mas significativas "
    "en el almacenamiento de energia, y en 2026, LFP representa mas del 80% de las nuevas "
    "implementaciones de BESS estacionario a nivel mundial.\n\n"
    "La unica ventaja restante de NMC - mayor densidad energetica - es en gran medida irrelevante "
    "para instalaciones estacionarias donde las restricciones de espacio rara vez son vinculantes. "
    "Para la gran mayoria de proyectos BESS, LFP es la opcion correcta.\n\n"
    "Tiene preguntas sobre que quimica de bateria es adecuada para su proyecto? Nuestro equipo de "
    "ingenieria puede ayudarle a evaluar ambas opciones."
)

# Article 7: Grid Frequency Regulation - the longest one
data["1883da43-1f06-4e92-b910-6da6f836480e"] = (
    "La regulacion de frecuencia de red es el servicio auxiliar de mayor valor disponible para los "
    "operadores de sistemas de almacenamiento de energia en baterias (BESS) en la actualidad. A "
    "diferencia del arbitraje energetico - donde los margenes se comprimen a medida que mas "
    "almacenamiento entra al mercado - la regulacion de frecuencia exige precios premium porque "
    "requiere velocidad, precision y confiabilidad que solo las baterias pueden ofrecer.\n\n"
    "En esta guia, analizamos como funcionan los mercados de regulacion de frecuencia, por que BESS "
    "supera a todas las tecnologias competidoras y como se ven los numeros de ingresos reales en los "
    "principales mercados globales.\n\n"
    "## Como Funcionan los Mercados de Regulacion de Frecuencia\n\n"
    "La frecuencia de la red debe mantenerse dentro de una banda estrecha alrededor de 50 Hz "
    "(o 60 Hz en America del Norte). Cada desviacion indica un desequilibrio entre generacion y carga. "
    "Los servicios de regulacion de frecuencia corrigen estas desviaciones en tiempo real.\n\n"
    "### Los Tres Niveles de Control de Frecuencia\n\n"
    "| Nivel | Tiempo de Respuesta | Duracion | Proveedor Tipico | Rol de BESS |\n"
    "|-------|--------------------|----------|------------------|-------------|\n"
    "| **Primario (FCR / PFR)** | 1-30 segundos | Hasta 15 minutos | BESS, hidro, turbinas de gas | Dominante |\n"
    "| **Secundario (aFRR / RegD)** | 30 seg-15 min | 15 min-1 hora | BESS, gas, hidro bombeada | Fuerte |\n"
    "| **Terciario (mFRR / Reserva)** | 15 min+ | 1-24 horas | Gas, carbon, hidro | Nicho |\n\n"
    "**Respuesta Rapida de Frecuencia (FFR)** es una categoria ultra-rapida emergente "
    "(respuesta <1 segundo) donde BESS no tiene competencia alguna. Mercados como Dynamic "
    "Containment del Reino Unido y Very Fast FCAS de Australia ya pagan primas extraordinarias "
    "por capacidad de respuesta en menos de un segundo.\n\n"
    "### Mecanismos Clave de Mercado\n\n"
    "- **Senales de regulacion hacia arriba y hacia abajo:** El operador de red envia una senal "
    "dinamica (actualizada cada 2-4 segundos) indicando la potencia de carga o descarga requerida. "
    "El BESS sigue esta senal en tiempo real.\n"
    "- **Compensacion por kilometraje:** Muchos mercados (PJM, CAISO, ERCOT) pagan basado en "
    "kilometraje - el total de MW de movimiento de regulacion entregado - no solo por capacidad "
    "reservada.\n"
    "- **Precios duales:** Separacion del pago por capacidad (por estar disponible) y pago por "
    "rendimiento (por la regulacion real entregada), con BESS ganando desproporcionadamente en "
    "el componente de rendimiento.\n\n"
    "## Por Que BESS Supera a Todos los Demas\n\n"
    "### Comparacion de Velocidad y Precision\n\n"
    "| Tecnologia | Tiempo de Respuesta | Precision | Costo de Desgaste |\n"
    "|------------|--------------------|-----------|------------------|\n"
    "| **BESS** | <200ms | >98% | Ciclos de bateria |\n"
    "| **Hidro bombeada** | 10-30 segundos | 85-95% | Desgaste mecanico |\n"
    "| **Turbina de gas** | 1-5 minutos | 90-95% | Ciclado termico |\n"
    "| **Volante de inercia** | <100ms | >95% | Desgaste de rodamientos |\n\n"
    "La combinacion de BESS de respuesta en menos de 200ms y precision superior al 98% significa "
    "que consistentemente obtiene las puntuaciones de rendimiento mas altas en los mercados de "
    "regulacion, cobrando primas que otras tecnologias simplemente no pueden alcanzar.\n\n"
    "## Ingresos Reales por Mercado\n\n"
    "### PJM (EE. UU.)\n\n"
    "**Servicio:** RegD (Regulacion Dinamica)\n"
    "**Ingreso tipico:** $30,000-80,000 por MW por ano\n"
    "**Impulsores clave:** Compensacion por kilometraje, altos diferenciales de rendimiento\n"
    "**Nota:** El mercado de regulacion de PJM es uno de los mas lucrativos a nivel mundial, "
    "con precios de compensacion de RegD que a menudo superan significativamente los precios "
    "de regulacion tradicional.\n\n"
    "### Reino Unido (National Grid ESO)\n\n"
    "**Servicio:** Dynamic Containment, FFR\n"
    "**Ingreso tipico:** L45,000-100,000 por MW por ano (~$57,000-127,000)\n"
    "**Impulsores clave:** Ventana de respuesta <1 segundo, altos precios de disponibilidad\n"
    "**Nota:** Dynamic Containment del Reino Unido es actualmente el servicio de frecuencia "
    "de mayor precio a nivel mundial, pagando primas por respuesta de menos de un segundo "
    "que solo BESS puede proporcionar.\n\n"
    "### Alemania (FCR)\n\n"
    "**Servicio:** FCR (Reserva de Control de Frecuencia Primaria)\n"
    "**Ingreso tipico:** 25,000-60,000 por MW por ano\n"
    "**Impulsores clave:** Subastas semanales, participacion de BESS en crecimiento\n"
    "**Nota:** El mercado FCR aleman ha visto cierta saturacion a medida que ingresa mas "
    "BESS, pero los precios siguen siendo atractivos para sistemas con bajos costos de capital.\n\n"
    "### Australia (AEMO)\n\n"
    "**Servicio:** FCAS (Servicios Auxiliares de Control de Frecuencia)\n"
    "**Ingreso tipico:** A$50,000-120,000 por MW por ano (~$33,000-80,000)\n"
    "**Impulsores clave:** Mercado FCAS unico de 8 servicios, eventos de contingencia de alto precio\n"
    "**Nota:** El mercado FCAS australiano es unico en ofrecer 8 servicios de frecuencia "
    "separados (subida/bajada x 4 velocidades), permitiendo que BESS acumule ingresos "
    "de multiples servicios simultaneamente.\n\n"
    "## Estrategias de Optimizacion de Ingresos\n\n"
    "### 1. Apilamiento de Servicios\n\n"
    "La mayoria de los BESS que participan en regulacion de frecuencia tambien pueden "
    "acumular ingresos de arbitraje energetico y reduccion de picos simultaneamente, "
    "siempre que el sistema de gestion de energia (EMS) este configurado para "
    "co-optimizar multiples fuentes de ingresos.\n\n"
    "### 2. Dimensionamiento para Mercados de Regulacion\n\n"
    "Para una participacion optima en regulacion de frecuencia:\n"
    "- **Relacion potencia/energia:** 1C a 4C (1 MW de potencia por 0.25-1 MWh de capacidad)\n"
    "- **Configuracion tipica:** Los sistemas de 2 horas (0.5C) ofrecen un buen equilibrio\n"
    "- **Minimo del mercado:** La mayoria de los mercados requieren 1 MW de capacidad minima\n\n"
    "### 3. Estrategia de Degradacion\n\n"
    "La regulacion de frecuencia implica ciclos superficiales (tipicamente 5-15% DoD), "
    "lo que causa significativamente menos degradacion que los ciclos completos de arbitraje "
    "energetico. Sin embargo, la alta frecuencia de ciclos (cientos por dia) significa que "
    "la vida calendario, no la vida util de ciclos, es a menudo el factor limitante.\n\n"
    "## Tendencias e Implicaciones del Mercado\n\n"
    "A medida que la penetracion de energia renovable aumenta a nivel mundial, la demanda de "
    "servicios de regulacion de frecuencia crece con ella. La generacion eolica y solar no "
    "proporcionan inercia ni respuesta de frecuencia de forma natural, creando una necesidad "
    "cada vez mayor de activos de respuesta rapida.\n\n"
    "Sin embargo, los precios de regulacion pueden disminuir a medida que mas BESS ingresa "
    "a estos mercados. Los primeros participantes en mercados emergentes de FFR (Europa del Este, "
    "Sudeste Asiatico, America Latina) probablemente capturen los retornos mas altos antes de "
    "que ocurra la saturacion.\n\n"
    "## Conclusion\n\n"
    "La regulacion de frecuencia de red sigue siendo la fuente de ingresos de mayor valor para "
    "los operadores de BESS, ofreciendo retornos anuales de $30,000-120,000 por MW dependiendo "
    "del mercado. La velocidad y precision inigualables de BESS lo convierten en la tecnologia "
    "dominante para este servicio, y la creciente penetracion de energia renovable solo aumentara "
    "la demanda de regulacion de frecuencia en los proximos anos.\n\n"
    "Para maximizar los ingresos, los operadores de BESS deben apuntar a mercados con altos "
    "diferenciales de rendimiento (PJM, Reino Unido), participar en multiples servicios auxiliares "
    "simultaneamente, y posicionarse temprano en mercados emergentes de FFR antes de que llegue "
    "la saturacion.\n\n"
    "Interesado en explorar oportunidades de ingresos por regulacion de frecuencia para su BESS? "
    "Nuestro equipo puede proporcionar analisis de ingresos especificos del mercado y "
    "recomendaciones de dimensionamiento del sistema."
)

with open('scripts/es_blog_bodies.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"All 7 articles translated! Total: {len(data)}")
for aid, body in data.items():
    print(f"  {aid[:8]}... | {len(body)} chars")
