"""Append Spanish translations for articles 3-5 to es_blog_bodies.json"""
import json

with open('scripts/es_blog_bodies.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Article 3: C&I Solar Storage Installation Guide
data["aa7c7fd8-8d65-4534-adab-2e86dfc2211c"] = (
    "Instalar un sistema de almacenamiento de energia en baterias comercial e industrial (C&I) es un proceso de multiples fases "
    "que requiere planificacion cuidadosa, ejecucion profesional y cumplimiento riguroso de seguridad. Esta guia le acompana a "
    "traves de cada paso, desde la evaluacion inicial del sitio hasta la puesta en marcha final.\n\n"
    "## Fase 1: Evaluacion del Sitio y Viabilidad\n\n"
    "### Analisis del Perfil de Carga\n\n"
    "Antes de cualquier otra cosa, necesita 12 meses de datos de medidores intervalos (15 minutos o por hora) para comprender "
    "los patrones de consumo de su instalacion. Las metricas clave incluyen:\n\n"
    "- **Demanda maxima (kW):** Determina la potencia nominal de la bateria\n"
    "- **Consumo energetico diario (kWh):** Determina la capacidad de la bateria\n"
    "- **Forma del perfil de carga:** Identifica ventanas optimas de carga/descarga\n"
    "- **Factor de potencia:** Puede requerir correccion junto con la instalacion del BESS\n\n"
    "### Inspeccion del Sitio\n\n"
    "Una inspeccion profesional del sitio debe evaluar:\n\n"
    "1. **Espacio disponible:** Los gabinetes de bateria C&I tipicamente requieren 1.5-3 m por cada 100 kWh. "
    "Considere el espacio libre para acceso de mantenimiento y ventilacion.\n"
    "2. **Infraestructura electrica:** Proximidad al tablero principal, capacidad del transformador y posiciones de interruptores disponibles.\n"
    "3. **Condiciones ambientales:** Rango de temperatura, humedad, zona sismica, riesgo de inundacion.\n"
    "4. **Condiciones de techo o suelo:** Para instalaciones exteriores, asegurese de que la superficie pueda soportar 3-6 toneladas por gabinete.\n\n"
    "### Estudio de Interconexion\n\n"
    "Su empresa electrica requerira un estudio de interconexion para evaluar el impacto del BESS en la red local. "
    "Esto tipicamente toma de 4 a 12 semanas dependiendo del tamano del sistema y la carga de trabajo de la empresa.\n\n"
    "## Fase 2: Diseno e Ingenieria del Sistema\n\n"
    "### Diseno Electrico\n\n"
    "- **Punto de interconexion:** La mayoria de los sistemas C&I se conectan del lado del cliente del medidor "
    "(detras del medidor), tipicamente a 480V o 400V.\n"
    "- **Dimensionamiento del transformador:** Asegurese de que el transformador existente pueda manejar el flujo "
    "de potencia bidireccional adicional. Puede requerirse un transformador dedicado para sistemas mas grandes.\n"
    "- **Diseno de proteccion:** Incluya interruptores de desconexion DC y AC, proteccion contra sobrecorriente "
    "y dispositivos de proteccion contra sobretensiones (SPD).\n"
    "- **Puesta a tierra:** Siga NEC Articulo 250 / IEC 60364 para sistemas de puesta a tierra adecuados.\n\n"
    "### Diseno Termico\n\n"
    "La gestion termica es critica tanto para la seguridad como para la vida util:\n\n"
    "- La refrigeracion liquida es el estandar de la industria para sistemas C&I > 100 kWh\n"
    "- Mantenga una diferencia de temperatura de celda < 3 C dentro de cada paquete\n"
    "- Asegure un flujo de aire adecuado alrededor de los gabinetes (minimo 1 metro de espacio libre)\n"
    "- Para instalaciones en climas frios, incluya calefaccion de bateria para operacion por debajo de 0 C\n\n"
    "### Diseno de Seguridad contra Incendios\n\n"
    "- Supresion de incendios integrada en el gabinete (aerosol, perfluorohexanona o rociado de agua)\n"
    "- Detectores de humo y gas (CO, H2) dentro de cada gabinete\n"
    "- Distancia de separacion entre gabinetes (tipicamente 1 metro o mas)\n"
    "- Plan de respuesta a emergencias y coordinacion con el departamento de bomberos local\n\n"
    "## Fase 3: Permisos y Aprobaciones\n\n"
    "### Permisos Tipicos Requeridos\n\n"
    "1. **Permiso de construccion:** Integridad estructural, cumplimiento de zonificacion\n"
    "2. **Permiso electrico:** Cableado, proteccion, puesta a tierra\n"
    "3. **Permiso de seguridad contra incendios:** Supresion, deteccion, acceso para bomberos\n"
    "4. **Acuerdo de interconexion:** Aprobacion de la empresa electrica para conexion a red\n"
    "5. **Evaluacion ambiental:** Puede requerirse para sistemas grandes o ubicaciones sensibles\n\n"
    "### Cronograma de Permisos\n\n"
    "Espere de 8 a 16 semanas para el proceso completo de permisos. Involucre a las autoridades locales temprano: "
    "los permisos de bomberos en particular pueden tomar mas tiempo del esperado.\n\n"
    "## Fase 4: Instalacion\n\n"
    "### Preparacion del Sitio\n\n"
    "- Preparacion de cimentacion (plataformas de concreto o bases de acero)\n"
    "- Mejoras de infraestructura electrica\n"
    "- Instalacion de conductos para cables de potencia y comunicacion\n"
    "- Instalacion de red de comunicaciones (fibra o Ethernet)\n\n"
    "### Instalacion de Equipos\n\n"
    "1. Entrega y colocacion de gabinetes (grua o montacargas)\n"
    "2. Conexiones electricas (potencia DC, potencia AC, puesta a tierra)\n"
    "3. Cableado de comunicaciones (Modbus TCP, CAN bus, Ethernet)\n"
    "4. Integracion del sistema de refrigeracion\n"
    "5. Conexion del sistema de supresion de incendios\n\n"
    "### Duracion Tipica\n\n"
    "- Sistemas pequenos (<500 kWh): 2-4 semanas\n"
    "- Sistemas medianos (500 kWh-2 MWh): 4-8 semanas\n"
    "- Sistemas grandes (>2 MWh): 8-16 semanas\n\n"
    "## Fase 5: Puesta en Marcha\n\n"
    "### Lista de Verificacion de Puesta en Marcha\n\n"
    "1. **Inspeccion visual:** Danos fisicos, conexiones correctas, etiquetado\n"
    "2. **Prueba de resistencia de aislamiento:** Verificar integridad electrica\n"
    "3. **Prueba de comunicacion:** Verificar comunicacion BMS, PCS, EMS\n"
    "4. **Prueba del sistema de refrigeracion:** Verificar rendimiento termico a plena carga\n"
    "5. **Prueba de supresion de incendios:** Prueba funcional de detectores y supresores\n"
    "6. **Ciclo de carga/descarga:** Verificar capacidad y eficiencia nominal\n"
    "7. **Prueba de conexion a red:** Verificar sincronizacion y calidad de potencia\n"
    "8. **Prueba de apagado de emergencia:** Verificar parada de emergencia y respuesta de seguridad\n\n"
    "### Documentacion\n\n"
    "Recopile toda la documentacion de puesta en marcha, incluyendo:\n"
    "- Informes de prueba\n"
    "- Planos conforme a obra\n"
    "- Manuales de operacion y mantenimiento\n"
    "- Certificados de garantia\n"
    "- Contactos de respuesta a emergencias\n\n"
    "## Conclusion\n\n"
    "Un proyecto de BESS C&I bien ejecutado tipicamente toma de 4 a 8 meses desde la evaluacion del sitio "
    "hasta la puesta en marcha. La clave del exito es una planificacion temprana, involucrar a profesionales "
    "experimentados y no tomar atajos en los procesos de permisos o puesta en marcha.\n\n"
    "Listo para comenzar su proyecto? Contacte a nuestro equipo para una consulta gratuita de viabilidad de instalacion."
)

# Article 4: Solar Storage Certification Guide
data["04a5a326-abaa-49b2-b520-75975cc001b4"] = (
    "Para que los sistemas de almacenamiento de energia en baterias (BESS) se desplieguen comercialmente, "
    "deben cumplir con una compleja red de requisitos de certificacion internacionales y regionales. "
    "Comprender estos estandares es esencial para desarrolladores de proyectos, contratistas EPC e integradores "
    "de sistemas. Esta guia desglosa las certificaciones clave y explica que significa cada una para su proyecto.\n\n"
    "## Por Que Importa la Certificacion\n\n"
    "Las certificaciones de almacenamiento en baterias sirven tres propositos criticos:\n\n"
    "1. **Garantia de seguridad:** Las certificaciones verifican que el sistema ha sido probado contra estandares "
    "de seguridad reconocidos, reduciendo el riesgo de fuga termica, incendio y peligros electricos.\n"
    "2. **Cumplimiento normativo:** La mayoria de las jurisdicciones requieren certificaciones especificas antes "
    "de otorgar permisos de instalacion o aprobacion de interconexion a la red.\n"
    "3. **Seguros y financiamiento:** Prestamistas y aseguradoras tipicamente requieren equipos certificados "
    "como condicion para el financiamiento y la cobertura del proyecto.\n\n"
    "## Estandares Basicos de Baterias\n\n"
    "### IEC 62619 - Requisitos de Seguridad para Baterias Industriales\n\n"
    "**Alcance:** Requisitos de seguridad para celdas y baterias secundarias de litio utilizadas en aplicaciones "
    "industriales, incluyendo BESS.\n\n"
    "**Requisitos clave:**\n"
    "- Prueba de abuso termico (calentar celdas a 130 C por 10 minutos)\n"
    "- Prueba de aplastamiento (aplicar fuerza igual a la masa de la celda x 1000g)\n"
    "- Prueba de sobrecarga (cargar al 150% del voltaje limite superior)\n"
    "- Prueba de cortocircuito externo\n"
    "- Prueba de caida (caida de 1m sobre concreto)\n\n"
    "**Donde se requiere:** UE, Asia-Pacifico, Medio Oriente, Africa - cada vez mas la linea base global para seguridad BESS.\n\n"
    "**Por que importa:** Este es el estandar de seguridad BESS mas ampliamente reconocido en el mundo. "
    "Si su sistema no cuenta con certificacion IEC 62619, enfrentara barreras significativas en la mayoria "
    "de los mercados internacionales.\n\n"
    "### UL 9540A - Metodo de Prueba para Evaluar la Propagacion de Incendios por Fuga Termica\n\n"
    "**Alcance:** Una metodologia de prueba (no un estandar de aprobacion/rechazo) que evalua las caracteristicas "
    "de propagacion de incendios en instalaciones BESS.\n\n"
    "**Requisitos clave:**\n"
    "- Pruebas a nivel de celda, modulo, unidad e instalacion\n"
    "- Medicion de emisiones de gas durante la fuga termica\n"
    "- Evaluacion de calor radiante y temperaturas de llama\n"
    "- Evaluacion de propagacion de incendios mas alla del contenedor\n\n"
    "**Donde se requiere:** America del Norte (requerido por NFPA 855 y la mayoria de los codigos de bomberos). "
    "Cada vez mas solicitado en otros mercados.\n\n"
    "**Por que importa:** Los datos de prueba UL 9540A son criticos para obtener aprobaciones de departamentos "
    "de bomberos y cumplir requisitos de codigos de construccion.\n\n"
    "### UN38.3 - Transporte de Mercancias Peligrosas\n\n"
    "**Alcance:** Requisitos de prueba para el transporte seguro de celdas y baterias de litio.\n\n"
    "**Requisitos clave:**\n"
    "- Simulacion de altitud (baja presion)\n"
    "- Ciclado termico (-40 C a +75 C)\n"
    "- Vibracion (sinusoidal)\n"
    "- Choque mecanico\n"
    "- Cortocircuito externo\n"
    "- Impacto/aplastamiento\n"
    "- Sobrecarga\n"
    "- Descarga forzada\n\n"
    "**Donde se requiere:** Obligatorio para envio internacional de todos los productos de baterias de litio "
    "por aire, mar o tierra.\n\n"
    "**Por que importa:** Sin UN38.3, no puede enviar legalmente productos de baterias de litio a traves "
    "de fronteras internacionales.\n\n"
    "### CE - Conformidad Europea\n\n"
    "**Alcance:** Declaracion obligatoria de conformidad para productos vendidos en el Espacio Economico Europeo.\n\n"
    "**Requisitos clave:**\n"
    "- Cumplimiento de Directivas de Bajo Voltaje (LVD) y Compatibilidad Electromagnetica (EMC)\n"
    "- Cumplimiento RoHS (Restriccion de Sustancias Peligrosas)\n"
    "- Documentacion de expediente tecnico\n"
    "- Declaracion de Conformidad del fabricante\n\n"
    "**Donde se requiere:** Union Europea, EEE.\n\n"
    "**Por que importa:** El marcado CE es obligatorio para el acceso al mercado europeo. "
    "Sin el, sus productos no pueden venderse legalmente en la UE.\n\n"
    "## Estrategia de Certificacion\n\n"
    "### Priorizacion para Proyectos Globales\n\n"
    "1. **Comenzar con IEC 62619** - es la base para la mayoria de los demas estandares\n"
    "2. **Agregar UN38.3** - requerido para la logistica, incluso si aun no se despliega en el extranjero\n"
    "3. **Apuntar a mercados regionales** con certificaciones especificas (UL para America del Norte, CE para Europa)\n"
    "4. **Planificar los plazos** - la certificacion completa de un nuevo producto BESS puede tomar de 6 a 18 meses\n\n"
    "### Bandera Roja a Evitar\n\n"
    "Desconfie de proveedores que afirman tener certificacion IEC sin especificar que estandar IEC, "
    "o que proporcionan certificados para el sistema de gestion de bateria (BMS) en lugar del sistema BESS completo.\n\n"
    "## Conclusion\n\n"
    "Las certificaciones no son solo obstaculos burocraticos - son su licencia para operar en mercados globales. "
    "Invierta en certificacion temprano en el desarrollo del producto, trabaje con laboratorios de prueba acreditados "
    "(TUV, UL, Intertek, SGS) y mantenga los certificados vigentes durante toda la vida util del producto.\n\n"
    "Necesita ayuda para navegar los requisitos de certificacion para su proyecto BESS? Nuestro equipo puede "
    "ayudarle a identificar y priorizar las certificaciones adecuadas para sus mercados objetivo."
)

# Article 5: How to Choose Energy Storage Supplier
data["852037bf-52b2-41fe-be11-d30766ab6a57"] = (
    "Seleccionar el proveedor adecuado de almacenamiento de energia en baterias es una de las decisiones mas "
    "importantes en cualquier proyecto BESS. Una eleccion incorrecta puede provocar retrasos en el cronograma, "
    "incidentes de seguridad, bajo rendimiento y costosas disputas de garantia. Este marco proporciona un enfoque "
    "estructurado para evaluar y comparar proveedores.\n\n"
    "## El Marco de Evaluacion de 15 Puntos\n\n"
    "### 1. Capacidad de Fabricacion\n\n"
    "**Que evaluar:**\n"
    "- Capacidad de produccion anual (GWh)\n"
    "- Integracion vertical (fabrican celdas, modulos y sistemas, o solo ensamblan?)\n"
    "- Ubicaciones de fabricacion y resiliencia de la cadena de suministro\n"
    "- Plazos de produccion y historial de entregas a tiempo\n\n"
    "**Senales de alerta:** Proveedores que no pueden proporcionar informes de auditoria de fabrica, "
    "aquellos con dependencia de celdas de una sola fuente, o aquellos con menos de 1 GWh de capacidad anual.\n\n"
    "### 2. Certificacion de Producto\n\n"
    "**Que evaluar:**\n"
    "- IEC 62619, UL 9540A, UN38.3, CE, GB/T 36276\n"
    "- Certificaciones especificas del mercado para sus regiones objetivo\n"
    "- Alcance de la certificacion (nivel de celda, modulo, sistema)\n"
    "- Fechas de vencimiento y planes de mantenimiento\n\n"
    "**Senales de alerta:** Certificaciones parciales, certificados vencidos o certificacion pendiente sin un cronograma confirmado.\n\n"
    "### 3. Rendimiento y Quimica de Celda\n\n"
    "**Que evaluar:**\n"
    "- Quimica de celda (LFP es el estandar de la industria para C&I/utility)\n"
    "- Vida util de ciclos a potencia nominal (minimo 6,000 a 0.5C; 8,000+ preferido)\n"
    "- Vida calendario (10+ anos)\n"
    "- Eficiencia de ida y vuelta a nivel de sistema (>87%)\n"
    "- Curva de degradacion y garantia de capacidad al final de la vida util (>=70% EOL)\n\n"
    "**Senales de alerta:** Quimica NMC para almacenamiento estacionario (riesgo de incendio), "
    "afirmaciones vagas de vida util de ciclos sin condiciones de prueba, o sin garantia explicita de capacidad EOL.\n\n"
    "### 4. Gestion Termica\n\n"
    "**Que evaluar:**\n"
    "- Tecnologia de refrigeracion (refrigeracion liquida preferida para C&I/utility)\n"
    "- Uniformidad de temperatura de celda (delta T <3 C dentro de un paquete)\n"
    "- Rendimiento en temperaturas ambiente de -20 C a +50 C\n"
    "- Capacidad de calefaccion para despliegue en climas frios\n\n"
    "**Senales de alerta:** Sistemas solo con refrigeracion por aire para >100 kWh, sin datos de uniformidad "
    "de temperatura, o sin funcion de calefaccion para climas frios.\n\n"
    "### 5. Seguridad contra Incendios\n\n"
    "**Que evaluar:**\n"
    "- Datos de prueba UL 9540A (propagacion de fuga termica)\n"
    "- Sistema de supresion de incendios integrado (aerosol, perfluorohexanona, rociado de agua)\n"
    "- Estrategia de contencion a nivel de gabinete\n"
    "- Monitoreo de gas (CO, H2, VOC)\n"
    "- Cumplimiento con NFPA 855, IFC 2024\n\n"
    "**Senales de alerta:** Sin datos de prueba UL 9540A, supresion de incendios solo a nivel de habitacion, "
    "o sin monitoreo de gas dentro del gabinete.\n\n"
    "### 6. Sistema de Gestion de Bateria (BMS)\n\n"
    "**Que evaluar:**\n"
    "- Arquitectura BMS (distribuida vs centralizada; se prefiere distribuida)\n"
    "- Monitoreo a nivel de celda (voltaje, temperatura, resistencia interna)\n"
    "- Balanceo de celda (activo vs pasivo; activo preferido)\n"
    "- Estimacion de SOC/SOH (precision <3% SOC, <5% SOH)\n"
    "- Protocolos de comunicacion (Modbus TCP, CAN, IEC 61850)\n\n"
    "**Senales de alerta:** BMS de un solo punto de falla, sin monitoreo a nivel de celda, o protocolos de comunicacion propietarios sin API abierta.\n\n"
    "### 7. Sistema de Gestion de Energia (EMS)\n\n"
    "**Que evaluar:**\n"
    "- Estrategias de control (reduccion de picos, arbitraje TOU, servicios auxiliares)\n"
    "- Capacidades de pronostico (carga, generacion solar, precios)\n"
    "- Monitoreo y control remoto (plataforma en la nube con aplicacion movil)\n"
    "- Capacidades de integracion (SCADA, DERMS, plataformas VPP)\n\n"
    "**Senales de alerta:** EMS con funcionalidad limitada (solo carga/descarga basica), sin monitoreo remoto, "
    "o sin capacidades de integracion con plataformas de terceros.\n\n"
    "### 8. Historial de Proyectos\n\n"
    "**Que evaluar:**\n"
    "- Numero de proyectos implementados (>100 preferido)\n"
    "- Capacidad total implementada (>500 MWh preferido)\n"
    "- Referencias de proyectos similares en tamano y aplicacion\n"
    "- Visitas al sitio e informes de rendimiento disponibles\n\n"
    "**Senales de alerta:** Menos de 20 proyectos implementados, sin referencias de proyectos de tamano similar, "
    "o renuencia a proporcionar contacto con clientes.\n\n"
    "### 9-15. Factores Restantes\n\n"
    "Los puntos restantes cubren: terminos de garantia (10 anos minimo), disponibilidad de repuestos, "
    "soporte tecnico local, requisitos de servicio O&M, estabilidad financiera de la empresa, cumplimiento "
    "de ciberseguridad y compromiso de sostenibilidad/ESG.\n\n"
    "## Marco de Puntuacion\n\n"
    "Califique a cada proveedor en los 15 puntos usando una escala de 1-5:\n\n"
    "| Puntuacion | Significado |\n"
    "|-----------|-------------|\n"
    "| 1 | Significativamente por debajo del estandar |\n"
    "| 2 | Por debajo del estandar |\n"
    "| 3 | Cumple con el estandar |\n"
    "| 4 | Supera el estandar |\n"
    "| 5 | Lider de la industria |\n\n"
    "**Puntuacion minima aprobatoria:** 45/75 (60%). No comprometa la seguridad ni la certificacion.\n\n"
    "## Conclusion\n\n"
    "Elegir un proveedor de BESS no se trata solo de precio - se trata de gestion de riesgos. "
    "Utilice este marco para eliminar sistematicamente a los proveedores de alto riesgo y seleccionar "
    "socios que brinden valor a largo plazo. Recuerde: la garantia mas barata no vale nada si la empresa "
    "ya no existe cuando necesite hacer un reclamo.\n\n"
    "Necesita ayuda para evaluar proveedores de BESS? Nuestro equipo puede proporcionar evaluaciones "
    "independientes de proveedores basadas en este marco de 15 puntos."
)

with open('scripts/es_blog_bodies.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done. Total articles in JSON: {len(data)}")
for aid, body in data.items():
    print(f"  {aid[:8]}... | {len(body)} chars")
